site_name: Documentation Template
site_url: https://telkomdev.github.io/documentation-template/
site_author: jimlyas
site_description: >-
  Template for developing Android Application Project in 

copyright: Copyright &copy; 2021 Telkom DEV

docs_dir: docs/content
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  custom_dir: docs/theme
  language: en
  features:
    - search
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telkomdev
    - icon: fontawesome/brands/medium
      link: https://medium.com/telkomdev
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCA5KKaClnatT5saGcKV8Cjw

nav:
  - Home: index.md